# Application
spring.application.name=spring-ai-application

# AI
spring.ai.google.genai.api-key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
spring.ai.google.genai.chat.model=XXXXXXXXXXXXXXXXXXXXXXXX
spring.ai.google.genai.chat.options.model=XXXXXXXXXXXXXXXXXXXXX

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?sslmode=disable
spring.datasource.username=XXXXXXXXXXXXXXX
spring.datasource.password=XXXXXXXXXXXXXXX
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
jwt.expiration=3600000